// Implement an OpenMP program to generate an array of random integers using the single construct. Then use the parallel for directive to compute the square of each element. Display the Thread ID that generates the array and the Thread IDs processing the elements.

#include <stdio.h>
#include <stdlib.h>
#include <omp.h>
#include <time.h>

int main()
{
    int n;

    printf("Enter the size of the array: ");
    scanf("%d", &n);

    int A[n], square[n];

    srand(time(NULL));

#pragma omp parallel
    {
#pragma omp single
        {
            int tid = omp_get_thread_num();

            printf("\nArray generated by thread %d\n", tid);

            for (int i = 0; i < n; i++)
                A[i] = rand() % 100;
        }

#pragma omp for
        for (int i = 0; i < n; i++)
        {
            int tid = omp_get_thread_num();
            square[i] = A[i] * A[i];
            printf("Element %d processed by Thread %d\n", i, tid);
        }
    }

    printf("\nOriginal Array:\n");
    for (int i = 0; i < n; i++)
        printf("%5d", A[i]);

    printf("\n\nSquared Array:\n");
    for (int i = 0; i < n; i++)
        printf("%5d", square[i]);

    printf("\n");

    return 0;
}